#!/bin/bash

SRC_DIR='/usr/src/tegra_multimedia_api'
DEST_DIR="$HOME/"

check_src()
{
    if ! [ -d "$SRC_DIR" ]; then
	echo 'You must install the Tegra Multimedia API on the target.'
	echo 'This can be done via SDK Manager'
	exit 1
    fi
}

install_deps()
{
    sudo apt-get -y install \
	 cmake \
	 build-essential \
	 pkg-config \
	 libx11-dev \
	 libgtk-3-dev \
	 libexpat1-dev \
	 libjpeg-dev \
	 libgstreamer1.0-dev \
	 gcc-6
}

copy_src()
{
    cp -r "$SRC_DIR" "$DEST_DIR"
}

perf_max()
{
    sudo nvpmodel -m 0
    sudo jetson_clocks
}

n_cpus()
{
    grep -c ^proc /proc/cpuinfo
}

build()
{
    pushd "${DEST_DIR}/tegra_multimedia_api/argus"
    mkdir build
    cd build
    cmake ..
    make -j$(n_cpus)
    sudo make install
    popd
}


check_src
install_deps
copy_src
perf_max
build
