#!/bin/bash
#
# Copyright (c) 2019-2020, D3 Engineering.  All rights reserved.
#

SRC_DIR_ARRAY=( \
    '/usr/src/jetson_multimedia_api'    # JP 4.3
    '/usr/src/tegra_multimedia_api'     # JP 4.2.X
)

DEST_DIR="$HOME/jetson_multimedia_api"

unset SRC_DIR

set -o errexit
set -o pipefail

find_src()
{
    for dir in "${SRC_DIR_ARRAY[@]}"; do
        if [[ -d "$dir" && -r "$dir" ]]; then
            SRC_DIR="$dir"
            break
        fi
    done
}

check_src()
{
    if [[ -z "${SRC_DIR+x}" ]]; then
        echo ''
        echo 'Error: Unable to find any source install paths:'
        for dir in "${SRC_DIR_ARRAY[@]}"; do
            printf "\t- %s\n" "$dir"
        done
        echo -e '\e[31m'
        echo 'Is Tegra Multimedia API installed on the target Jetson board?'
        echo 'This can be done via SDK Manager'
        echo -e '\e[0m'
        exit 1
    fi
}

install_deps()
{
    sudo apt-get -y install \
     cmake \
     build-essential \
     pkg-config \
     libx11-dev \
     libgtk-3-dev \
     libexpat1-dev \
     libjpeg-dev \
     libgstreamer1.0-dev \
     gcc-6
}

copy_src()
{
    mkdir -p "$DEST_DIR"
    cp -r "$SRC_DIR"/* "$DEST_DIR"
}

perf_max()
{
    sudo nvpmodel -m 0
    sudo jetson_clocks
}

n_cpus()
{
    grep -c ^proc /proc/cpuinfo
}

build()
{
    pushd "${DEST_DIR}/argus"
    mkdir -p build
    cd build
    cmake ..
    make -j$(n_cpus)
    sudo make install
    popd
}

find_src
check_src
install_deps
copy_src
perf_max
build
echo -e '\e[32mTegra Multimedia API installed!\e[0m'
