#!/bin/bash

# This script assigns the 6 available overlays to fb0

if [ -e /sys/class/graphics/fb2 ]
then
    cd /sys/class/graphics/fb2
    # turn off display
    echo 4 > blank
    # disable all overlays for the display
    echo 0x0 > device/win_mask
fi

cd /sys/class/graphics/fb1
# turn off display
echo 4 > blank
# disable all overlays for the display
echo 0x0 > device/win_mask

cd /sys/class/graphics/fb0
# turn off the display
echo 4 > blank
# disable all overlays for the display
echo 0x0 > device/win_mask

# Assign all 6 available overlays to the display
echo 0x3f > device/win_mask

# Turn the display on
echo 0 > blank
