# This is included in the kernel make system. Just add the dts you
# want compiled to d3-dtb-y

# Jetson Camera Interface (6ch SerDes card)
d3-dtb-y += d3-xavier-6x-serdes.dtb
d3-dtb-y += d3-orin-6x-serdes.dtb

# Xavier 16x FPD-Link Interface Card
d3-dtb-y += d3-xavier-16x-fpdlink.dtb

# NXC - FPDLink
d3-dtb-y += d3-nxc-emmc.dtb d3-nxc-sdcard.dtb
