# This is included in the kernel make system. Just add the dts you
# want compiled to d3-dtb-y

# RSP - FPDLINK3
d3-dtb-y += d3-tx2-rsp-fpdlink.dtb

# RSP - GMSL2
#d3-dtb-y += d3-tx2-rsp-gmsl2.dtb

# Tx2 Jetson Camera Interface (6ch serdes card)
d3-dtb-y += d3-tx2-6x-serdes.dtb

# Xavier Jetson Camera Interface (6ch serdes card)
d3-dtb-y += d3-xavier-6x-serdes.dtb

# Xavier 16x FPD-Link Interface Card
d3-dtb-y += d3-xavier-16x-fpdlink.dtb

# NXC - FPDLink
d3-dtb-y += d3-nxc-fpdlink.dtb
