# This is included in the kernel make system. Just add the dts you
# want compiled to d3-dtb-y

# RSP - FPDLINK3
d3-dtb-y += d3-rsp-fpdlink-imx390.dtb
d3-dtb-y += d3-rsp-fpdlink-imx390rcm.dtb
d3-dtb-y += d3-rsp-fpdlink-ov10640.dtb
# d3-dtb-y += d3-rsp-fpdlink-vg6768.dtb

# RSP - GMSL2
#d3-dtb-y += d3-rsp-gmsl2-ar820.dtb

# Tx2 CIC
d3-dtb-y += d3-ncic-imx390.dtb
d3-dtb-y += d3-ncic-imx390rcm.dtb
d3-dtb-y += d3-ncic-ov10640.dtb
#d3-dtb-y += d3-ncic-vg6768.dtb

# Xavier CIC
d3-dtb-y += d3-xavier-ncic-ov10640.dtb
d3-dtb-y += d3-xavier-ncic-imx390.dtb
d3-dtb-y += d3-xavier-ncic-imx390rcm.dtb


# Xavier 2xOcto
d3-dtb-y += d3-xavier-2xocto-ov10640.dtb
d3-dtb-y += d3-xavier-2xocto-imx390.dtb
d3-dtb-y += d3-xavier-2xocto-imx390rcm.dtb
