#include "ar0234_tables.h"

// Start stream will enable streaming and ensure the AR0234 can receive frame
// sync input. Will not put the AR0234 into a frame sync mode, but allows
// for the reading of the signal.
const struct reg_tbl_t ar0234_start[] = {
	{ .action = SET_FIELD, .addr = 0x301a, .mask = 0x904, .val = 0x904 },
	{ .action = DELAY_MS, .val = 128 },
	{ .action = END_TABLE }
};

const struct reg_tbl_t ar0234_stop[] = {
	{ .action = SET_FIELD, .addr = 0x301a, .mask = 0x4, .val = 0x0 },
	{ .action = DELAY_MS, .val = 100 },
	{ .action = END_TABLE }
};

const struct reg_tbl_t ar0234_1080p_30fps[] = {
	// This file was generated by RegisterWizard.exe for AR0234CS.  Version: 6. 1. 11. 57619 (Build Date: Feb  8 2022)
	//
	// [PLL PARAMETERS]
	// Target Pixel Frequency: 45 MHz
	// Input Clock Frequency: 27 MHz
	//
	// Actual Pixel Clock: 45 MHz
	//
	// pre_pll_clk_div (N+1 Value) = 3
	// pll_multiplier  (2M Value) = 50
	// Fvco = 450 MHz
	// vt_sys_clk_div (P1) = 2
	// vt_pix_clk_div (P2) = 5
	// op_sys_clk_div (P3) = 2
	// op_pix_clk_div (WCD)= 10
	// Serial Bit Clock: 225 MHz
	// Word Clock: 45 MHz
	// Pixel Clock: 45 MHz
	// Sensor Logic Data Rate: 180 Mpix/s
	// MIPI Data Rate: 180 Mpix/s
	// Serial data Rate: 450 Mbit/s
	//
	// [IMAGE PARAMETERS]
	// Requested Frames Per Second: 30
	// Output Columns: 1920
	// Output Rows: 1080
	// Use Binning: Unchecked
	// Cols Skipping: Unchecked
	// Rows Skipping: Unchecked
	// Blanking Computation: VB Max then HB
	//
	// Max Frame Time: 33.3333 msec
	// Max Frame Clocks: 1500000.0 clocks  (45 MHz)
	//
	// Subsampling: 1x cols, 1x rows, Bin Mode: No
	// Horiz clks:  612 total
	// Vert  rows:  1080 active + 1365 blank = 2445 total
	// Extra Delay: 3660 clocks
	// Columns FOV: 1920
	// Rows FOV   : 1080
	// Output Cols: 1920
	// Output Rows: 1080
	// Actual Frame Clocks: 1496340 clocks
	// Row Time: 13.600 usec.
	// Integration Time: 30 msec.
	// Frame time: 33.252000 msec
	// Maximum Frame Rate allowed: 66.784fps
	// Frames per Sec: 30.012 fps
	//
	// Operation Mode: Linear

	// [PLL_settings]
	{ .action = WRITE_REG, .addr = 0x302A, .val = 0x0005 },	//VT_PIX_CLK_DIV = 5
	{ .action = WRITE_REG, .addr = 0x302C, .val = 0x0002 },	//VT_SYS_CLK_DIV = 2
	{ .action = WRITE_REG, .addr = 0x302E, .val = 0x0003 },	//PRE_PLL_CLK_DIV = 3
	{ .action = WRITE_REG, .addr = 0x3030, .val = 0x0032 },	//PLL_MULTIPLIER = 50
	{ .action = WRITE_REG, .addr = 0x3036, .val = 0x000A },	//OP_PIX_CLK_DIV = 10
	{ .action = WRITE_REG, .addr = 0x3038, .val = 0x0002 },	//OP_SYS_CLK_DIV = 2
	{ .action = SET_FIELD, .addr = 0x30B0, .mask = 0x4000, .val = 0x0000 }, //DIGITAL_TEST, bits 0x4000 = 0
	{ .action = WRITE_REG, .addr = 0x31B0, .val = 0x004C },	//FRAME_PREAMBLE = 76
	{ .action = WRITE_REG, .addr = 0x31B2, .val = 0x003C },	//LINE_PREAMBLE = 60
	{ .action = WRITE_REG, .addr = 0x31B4, .val = 0x31C5 },	//MIPI_TIMING_0 = 12741
	{ .action = WRITE_REG, .addr = 0x31B6, .val = 0x214C },	//MIPI_TIMING_1 = 8524
	{ .action = WRITE_REG, .addr = 0x31B8, .val = 0x5048 },	//MIPI_TIMING_2 = 20552
	{ .action = WRITE_REG, .addr = 0x31BA, .val = 0x0186 },	//MIPI_TIMING_3 = 390
	{ .action = WRITE_REG, .addr = 0x31BC, .val = 0x8805 },	//MIPI_TIMING_4 = 34821
	{ .action = WRITE_REG, .addr = 0x3354, .val = 0x002B }, //MIPI_CNTRL = 43
	// [Timing_settings]
	{ .action = WRITE_REG, .addr = 0x301A, .val = 0x2058 },	//RESET_REGISTER = 8280
	{ .action = WRITE_REG, .addr = 0x31AE, .val = 0x0204 },	//SERIAL_FORMAT = 516
	{ .action = WRITE_REG, .addr = 0x3002, .val = 0x0044 },	//Y_ADDR_START = 68
	{ .action = WRITE_REG, .addr = 0x3004, .val = 0x0008 },	//X_ADDR_START = 8
	{ .action = WRITE_REG, .addr = 0x3006, .val = 0x047B },	//Y_ADDR_END = 1147
	{ .action = WRITE_REG, .addr = 0x3008, .val = 0x0787 },	//X_ADDR_END = 1927
	{ .action = WRITE_REG, .addr = 0x300A, .val = 0x098D },	//FRAME_LENGTH_LINES = 2445
	{ .action = WRITE_REG, .addr = 0x300C, .val = 0x0264 },	//LINE_LENGTH_PCK = 612
	{ .action = WRITE_REG, .addr = 0x3012, .val = 0x02DF },	//COARSE_INTEGRATION_TIME = 2205
	{ .action = WRITE_REG, .addr = 0x31AC, .val = 0x0A0A },	//DATA_FORMAT_BITS = 2570
	{ .action = WRITE_REG, .addr = 0x306E, .val = 0x9010 },	//DATAPATH_SELECT = 36880
	{ .action = WRITE_REG, .addr = 0x30A2, .val = 0x0001 },	//X_ODD_INC = 1
	{ .action = WRITE_REG, .addr = 0x30A6, .val = 0x0001 },	//Y_ODD_INC = 1
	{ .action = WRITE_REG, .addr = 0x3082, .val = 0x0003 },	//OPERATION_MODE_CTRL = 3
	{ .action = WRITE_REG, .addr = 0x3040, .val = 0x0000 },	//READ_MODE = 0
	{ .action = WRITE_REG, .addr = 0x31D0, .val = 0x0000 },	//COMPANDING = 0
	{ .action = WRITE_REG, .addr = 0x301A, .val = 0x205C },	//RESET_REGISTER = 8284
	{ .action = END_TABLE },
};

#if 0
const struct reg_tbl_t ar0234_1080p_30fps[] = {
	// This file was generated by RegisterWizard.exe for AR0234CS.  Version: 6. 1. 11. 57619 (Build Date: Feb  8 2022)
	// 
	// [PLL PARAMETERS]
	// Target Pixel Frequency: 22.500 MHz
	// Input Clock Frequency: 27 MHz
	// 
	// Actual Pixel Clock: 22.500 MHz
	// 
	// pre_pll_clk_div (N+1 Value) = 2
	// pll_multiplier  (2M Value) = 50
	// Fvco = 675 MHz
	// vt_sys_clk_div (P1) = 6
	// vt_pix_clk_div (P2) = 5
	// op_sys_clk_div (P3) = 6
	// op_pix_clk_div (WCD)= 10
	// Serial Bit Clock: 112.500 MHz
	// Word Clock: 22.500 MHz
	// Pixel Clock: 22.500 MHz
	// Sensor Logic Data Rate: 90 Mpix/s
	// MIPI Data Rate: 90 Mpix/s
	// Serial data Rate: 225 Mbit/s
	// 
	// [IMAGE PARAMETERS]
	// Requested Frames Per Second: 30
	// Output Columns: 1920
	// Output Rows: 1080
	// Use Binning: Unchecked
	// Cols Skipping: Checked
	// Rows Skipping: Checked
	// Blanking Computation: VB Max then HB
	// 
	// Max Frame Time: 33.3333 msec
	// Max Frame Clocks: 750000.0 clocks  (22.50 MHz)
	// 
	// Subsampling: 1x cols, 1x rows, Bin Mode: No
	// Horiz clks:  612 total
	// Vert  rows:  1080 active + 140 blank = 1220 total
	// Extra Delay: 3360 clocks
	// Columns FOV: 1920
	// Rows FOV   : 1080
	// Output Cols: 1920
	// Output Rows: 1080
	// Actual Frame Clocks: 746640 clocks
	// Row Time: 27.200 usec.
	// Integration Time: 10 msec.
	// Frame time: 33.184000 msec
	// Maximum Frame Rate allowed: 33.392fps
	// Frames per Sec: 30.012 fps
	// 
	// Operation Mode: Linear

	{ .action = WRITE_REG, .addr = 0x302A, .val = 0x0005 },	// VT_PIX_CLK_DIV = 5
	{ .action = WRITE_REG, .addr = 0x302C, .val = 0x0006 },	// VT_SYS_CLK_DIV = 2
	{ .action = WRITE_REG, .addr = 0x302E, .val = 0x0002 },	// PRE_PLL_CLK_DIV = 2
	{ .action = WRITE_REG, .addr = 0x3030, .val = 0x0032 },	// PLL_MULTIPLIER = 50
	{ .action = WRITE_REG, .addr = 0x3036, .val = 0x000A },	// OP_PIX_CLK_DIV = 10
	{ .action = WRITE_REG, .addr = 0x3038, .val = 0x0006 },	// OP_SYS_CLK_DIV = 2
	{ .action = SET_FIELD, .addr = 0x30B0, .mask = 0x4000, .val = 0x0000},	// DIGITAL_TEST, bits 0x4000 = 0
	{ .action = WRITE_REG, .addr = 0x31B0, .val = 0x0030 },	// FRAME_PREAMBLE = 48
	{ .action = WRITE_REG, .addr = 0x31B2, .val = 0x002c },	// LINE_PREAMBLE = 44
	{ .action = WRITE_REG, .addr = 0x31B4, .val = 0x2144 },	// MIPI_TIMING_0 = 8516
	{ .action = WRITE_REG, .addr = 0x31B6, .val = 0x10c6 },	// MIPI_TIMING_1 = 4294
	{ .action = WRITE_REG, .addr = 0x31B8, .val = 0x3047 },	// MIPI_TIMING_2 = 12359
	{ .action = WRITE_REG, .addr = 0x31BA, .val = 0x0103 },	// MIPI_TIMING_3 = 259
	{ .action = WRITE_REG, .addr = 0x31BC, .val = 0x8503 },	// MIPI_TIMING_4 = 34051
	{ .action = WRITE_REG, .addr = 0x3354, .val = 0x002B },	// MIPI_CNTRL = 43
	{ .action = WRITE_REG, .addr = 0x301A, .val = 0x2058 },	// RESET_REGISTER = 8280
	{ .action = WRITE_REG, .addr = 0x31AE, .val = 0x0204 },	// SERIAL_FORMAT = 516
	{ .action = WRITE_REG, .addr = 0x3002, .val = 0x0044 },	// Y_ADDR_START = 68
	{ .action = WRITE_REG, .addr = 0x3004, .val = 0x0008 },	// X_ADDR_START = 8
	{ .action = WRITE_REG, .addr = 0x3006, .val = 0x047B },	// Y_ADDR_END = 1147
	{ .action = WRITE_REG, .addr = 0x3008, .val = 0x0787 },	// X_ADDR_END = 1927
	{ .action = WRITE_REG, .addr = 0x300A, .val = 0x04c4 },	// FRAME_LENGTH_LINES = 1220
	{ .action = WRITE_REG, .addr = 0x300C, .val = 0x0264 },	// LINE_LENGTH_PCK = 612
	{ .action = WRITE_REG, .addr = 0x3012, .val = 0x016f },	// COARSE_INTEGRATION_TIME = 1102
	{ .action = WRITE_REG, .addr = 0x31AC, .val = 0x0A0A },	// DATA_FORMAT_BITS = 2570
	{ .action = WRITE_REG, .addr = 0x306E, .val = 0x9010 },	// DATAPATH_SELECT = 36880
	{ .action = WRITE_REG, .addr = 0x30A2, .val = 0x0001 },	// X_ODD_INC = 1
	{ .action = WRITE_REG, .addr = 0x30A6, .val = 0x0001 },	// Y_ODD_INC = 1
	{ .action = WRITE_REG, .addr = 0x3082, .val = 0x0003 },	// OPERATION_MODE_CTRL = 3
	{ .action = WRITE_REG, .addr = 0x3040, .val = 0x0000 },	// READ_MODE = 0
	{ .action = WRITE_REG, .addr = 0x31D0, .val = 0x0000 },	// COMPANDING = 0
	{ .action = WRITE_REG, .addr = 0x301A, .val = 0x2058 },	// RESET_REGISTER = 8284
	{ .action = END_TABLE }
};
#endif

const struct reg_tbl_t ar0234_1080p_60fps[] = {
	// This file was generated by RegisterWizard.exe for AR0234CS.  Version: 6. 1. 11. 57619 (Build Date: Feb  8 2022)
	// 
	// [PLL PARAMETERS]
	// Target Pixel Frequency: 45 MHz
	// Input Clock Frequency: 27 MHz
	// 
	// Actual Pixel Clock: 45 MHz
	// 
	// pre_pll_clk_div (N+1 Value) = 3
	// pll_multiplier  (2M Value) = 50
	// Fvco = 450 MHz
	// vt_sys_clk_div (P1) = 2
	// vt_pix_clk_div (P2) = 5
	// op_sys_clk_div (P3) = 2
	// op_pix_clk_div (WCD)= 10
	// Serial Bit Clock: 225 MHz
	// Word Clock: 45 MHz
	// Pixel Clock: 45 MHz
	// Sensor Logic Data Rate: 180 Mpix/s
	// MIPI Data Rate: 180 Mpix/s
	// Serial data Rate: 450 Mbit/s
	// 
	// [IMAGE PARAMETERS]
	// Requested Frames Per Second: 60
	// Output Columns: 1920
	// Output Rows: 1080
	// Use Binning: Unchecked
	// Cols Skipping: Checked
	// Rows Skipping: Checked
	// Blanking Computation: VB Max then HB
	// 
	// Max Frame Time: 16.6667 msec
	// Max Frame Clocks: 750000.0 clocks  (45 MHz)
	// 
	// Subsampling: 1x cols, 1x rows, Bin Mode: No
	// Horiz clks:  612 total
	// Vert  rows:  1080 active + 140 blank = 1220 total
	// Extra Delay: 3360 clocks
	// Columns FOV: 1920
	// Rows FOV   : 1080
	// Output Cols: 1920
	// Output Rows: 1080
	// Actual Frame Clocks: 746640 clocks
	// Row Time: 13.600 usec.
	// Integration Time: 16 msec.
	// Frame time: 16.592000 msec
	// Maximum Frame Rate allowed: 66.784fps
	// Frames per Sec: 60.024 fps
	// 
	// Operation Mode: Linear
	{ .action = WRITE_REG, .addr = 0x302A, .val = 0x0005 },		//VT_PIX_CLK_DIV = 5
	{ .action = WRITE_REG, .addr = 0x302C, .val = 0x0002 },		//VT_SYS_CLK_DIV = 2
	{ .action = WRITE_REG, .addr = 0x302E, .val = 0x0003 },		//PRE_PLL_CLK_DIV = 3
	{ .action = WRITE_REG, .addr = 0x3030, .val = 0x0032 },		//PLL_MULTIPLIER = 50
	{ .action = WRITE_REG, .addr = 0x3036, .val = 0x000A },		//OP_PIX_CLK_DIV = 10
	{ .action = WRITE_REG, .addr = 0x3038, .val = 0x0002 },		//OP_SYS_CLK_DIV = 2
	{ .action = WRITE_REG, .addr = 0x30B0, .val = 0x0000 },		//DIGITAL_TEST, bits 0x4000 = 0
	{ .action = WRITE_REG, .addr = 0x31B0, .val = 0x004C },		//FRAME_PREAMBLE = 76
	{ .action = WRITE_REG, .addr = 0x31B2, .val = 0x003C },		//LINE_PREAMBLE = 60
	{ .action = WRITE_REG, .addr = 0x31B4, .val = 0x31C5 },		//MIPI_TIMING_0 = 12741
	{ .action = WRITE_REG, .addr = 0x31B6, .val = 0x214C },		//MIPI_TIMING_1 = 8524
	{ .action = WRITE_REG, .addr = 0x31B8, .val = 0x5048 },		//MIPI_TIMING_2 = 20552
	{ .action = WRITE_REG, .addr = 0x31BA, .val = 0x0186 },		//MIPI_TIMING_3 = 390
	{ .action = WRITE_REG, .addr = 0x31BC, .val = 0x8805 },		//MIPI_TIMING_4 = 34821
	{ .action = WRITE_REG, .addr = 0x3354, .val = 0x002B },		//MIPI_CNTRL = 43
	{ .action = WRITE_REG, .addr = 0x301A, .val = 0x2058 },		//RESET_REGISTER = 8280
	{ .action = WRITE_REG, .addr = 0x31AE, .val = 0x0204 },		//SERIAL_FORMAT = 516
	{ .action = WRITE_REG, .addr = 0x3002, .val = 0x0044 },		//Y_ADDR_START = 68
	{ .action = WRITE_REG, .addr = 0x3004, .val = 0x0008 },		//X_ADDR_START = 8
	{ .action = WRITE_REG, .addr = 0x3006, .val = 0x047B },		//Y_ADDR_END = 1147
	{ .action = WRITE_REG, .addr = 0x3008, .val = 0x0787 },		//X_ADDR_END = 1927
	{ .action = WRITE_REG, .addr = 0x300A, .val = 0x04C4 },		//FRAME_LENGTH_LINES = 1220
	{ .action = WRITE_REG, .addr = 0x300C, .val = 0x0264 },		//LINE_LENGTH_PCK = 612
	{ .action = WRITE_REG, .addr = 0x3012, .val = 0x0498 },		//COARSE_INTEGRATION_TIME = 1176
	{ .action = WRITE_REG, .addr = 0x31AC, .val = 0x0A0A },		//DATA_FORMAT_BITS = 2570
	{ .action = WRITE_REG, .addr = 0x306E, .val = 0x9010 },		//DATAPATH_SELECT = 36880
	{ .action = WRITE_REG, .addr = 0x30A2, .val = 0x0001 },		//X_ODD_INC = 1
	{ .action = WRITE_REG, .addr = 0x30A6, .val = 0x0001 },		//Y_ODD_INC = 1
	{ .action = WRITE_REG, .addr = 0x3082, .val = 0x0003 },		//OPERATION_MODE_CTRL = 3
	{ .action = WRITE_REG, .addr = 0x3040, .val = 0x0000 },		//READ_MODE = 0
	{ .action = WRITE_REG, .addr = 0x31D0, .val = 0x0000 },		//COMPANDING = 0
	{ .action = WRITE_REG, .addr = 0x301A, .val = 0x2058 },		//RESET_REGISTER = 8284
	{ .action = END_TABLE }
};


const struct reg_tbl_t ar0234_1200p_60fps[] = {
	// This file was generated by RegisterWizard.exe for AR0234CS.  Version: 6. 1. 11. 57619 (Build Date: Feb  8 2022)
	// 
	// [PLL PARAMETERS]
	// Target Pixel Frequency: 45 MHz
	// Input Clock Frequency: 27 MHz
	// 
	// Actual Pixel Clock: 45 MHz
	// 
	// pre_pll_clk_div (N+1 Value) = 3
	// pll_multiplier  (2M Value) = 50
	// Fvco = 450 MHz
	// vt_sys_clk_div (P1) = 2
	// vt_pix_clk_div (P2) = 5
	// op_sys_clk_div (P3) = 2
	// op_pix_clk_div (WCD)= 10
	// Serial Bit Clock: 225 MHz
	// Word Clock: 45 MHz
	// Pixel Clock: 45 MHz
	// Sensor Logic Data Rate: 180 Mpix/s
	// MIPI Data Rate: 180 Mpix/s
	// Serial data Rate: 450 Mbit/s
	// 
	// [IMAGE PARAMETERS]
	// Requested Frames Per Second: 60
	// Output Columns: 1920
	// Output Rows: 1200
	// Use Binning: Unchecked
	// Cols Skipping: Checked
	// Rows Skipping: Checked
	// Blanking Computation: VB Max then HB
	// 
	// Max Frame Time: 16.6667 msec
	// Max Frame Clocks: 750000.0 clocks  (45 MHz)
	// 
	// Subsampling: 1x cols, 1x rows, Bin Mode: No
	// Horiz clks:  612 total
	// Vert  rows:  1200 active + 20 blank = 1220 total
	// Extra Delay: 3360 clocks
	// Columns FOV: 1920
	// Rows FOV   : 1200
	// Output Cols: 1920
	// Output Rows: 1200
	// Actual Frame Clocks: 746640 clocks
	// Row Time: 13.600 usec.
	// Integration Time: 10 msec.
	// Frame time: 16.592000 msec
	// Maximum Frame Rate allowed: 60.221fps
	// Frames per Sec: 60.024 fps
	// 
	// Operation Mode: Linear

	{ .action = WRITE_REG, .addr = 0x302A, .val = 0x0005 },		//VT_PIX_CLK_DIV = 5
	{ .action = WRITE_REG, .addr = 0x302C, .val = 0x0002 },		//VT_SYS_CLK_DIV = 2
	{ .action = WRITE_REG, .addr = 0x302E, .val = 0x0003 },		//PRE_PLL_CLK_DIV = 3
	{ .action = WRITE_REG, .addr = 0x3030, .val = 0x0032 },		//PLL_MULTIPLIER = 50
	{ .action = WRITE_REG, .addr = 0x3036, .val = 0x000A },		//OP_PIX_CLK_DIV = 10
	{ .action = WRITE_REG, .addr = 0x3038, .val = 0x0002 },		//OP_SYS_CLK_DIV = 2
	{ .action = WRITE_REG, .addr = 0x30B0, .val = 0x0000 },		//DIGITAL_TEST, bits 0x4000 = 0
	{ .action = WRITE_REG, .addr = 0x31B0, .val = 0x004C },		//FRAME_PREAMBLE = 76
	{ .action = WRITE_REG, .addr = 0x31B2, .val = 0x003C },		//LINE_PREAMBLE = 60
	{ .action = WRITE_REG, .addr = 0x31B4, .val = 0x31C5 },		//MIPI_TIMING_0 = 12741
	{ .action = WRITE_REG, .addr = 0x31B6, .val = 0x214C },		//MIPI_TIMING_1 = 8524
	{ .action = WRITE_REG, .addr = 0x31B8, .val = 0x5048 },		//MIPI_TIMING_2 = 20552
	{ .action = WRITE_REG, .addr = 0x31BA, .val = 0x0186 },		//MIPI_TIMING_3 = 390
	{ .action = WRITE_REG, .addr = 0x31BC, .val = 0x8805 },		//MIPI_TIMING_4 = 34821
	{ .action = WRITE_REG, .addr = 0x3354, .val = 0x002B },		//MIPI_CNTRL = 43
	{ .action = WRITE_REG, .addr = 0x301A, .val = 0x2058 },		//RESET_REGISTER = 8280
	{ .action = WRITE_REG, .addr = 0x31AE, .val = 0x0204 },		//SERIAL_FORMAT = 516
	{ .action = WRITE_REG, .addr = 0x3002, .val = 0x0008 },		//Y_ADDR_START = 8
	{ .action = WRITE_REG, .addr = 0x3004, .val = 0x0008 },		//X_ADDR_START = 8
	{ .action = WRITE_REG, .addr = 0x3006, .val = 0x04B7 },		//Y_ADDR_END = 1207
	{ .action = WRITE_REG, .addr = 0x3008, .val = 0x0787 },		//X_ADDR_END = 1927
	{ .action = WRITE_REG, .addr = 0x300A, .val = 0x04C4 },		//FRAME_LENGTH_LINES = 1220
	{ .action = WRITE_REG, .addr = 0x300C, .val = 0x0264 },		//LINE_LENGTH_PCK = 612
	{ .action = WRITE_REG, .addr = 0x3012, .val = 0x02DF },		//COARSE_INTEGRATION_TIME = 735
	{ .action = WRITE_REG, .addr = 0x31AC, .val = 0x0A0A },		//DATA_FORMAT_BITS = 2570
	{ .action = WRITE_REG, .addr = 0x306E, .val = 0x9010 },		//DATAPATH_SELECT = 36880
	{ .action = WRITE_REG, .addr = 0x30A2, .val = 0x0001 },		//X_ODD_INC = 1
	{ .action = WRITE_REG, .addr = 0x30A6, .val = 0x0001 },		//Y_ODD_INC = 1
	{ .action = WRITE_REG, .addr = 0x3082, .val = 0x0003 },		//OPERATION_MODE_CTRL = 3
	{ .action = WRITE_REG, .addr = 0x3040, .val = 0x0000 },		//READ_MODE = 0
	{ .action = WRITE_REG, .addr = 0x31D0, .val = 0x0000 },		//COMPANDING = 0
	{ .action = WRITE_REG, .addr = 0x301A, .val = 0x2058 },		//RESET_REGISTER = 8284
	{ .action = END_TABLE }
};

const struct reg_tbl_t ar0234_720p_60fps[] = {
	// This file was generated by RegisterWizard.exe for AR0234CS.  Version: 6. 1. 11. 57619 (Build Date: Feb  8 2022)
	// 
	// [PLL PARAMETERS]
	// Target Pixel Frequency: 45 MHz
	// Input Clock Frequency: 27 MHz
	// 
	// Actual Pixel Clock: 45 MHz
	// 
	// pre_pll_clk_div (N+1 Value) = 3
	// pll_multiplier  (2M Value) = 50
	// Fvco = 450 MHz
	// vt_sys_clk_div (P1) = 2
	// vt_pix_clk_div (P2) = 5
	// op_sys_clk_div (P3) = 2
	// op_pix_clk_div (WCD)= 10
	// Serial Bit Clock: 225 MHz
	// Word Clock: 45 MHz
	// Pixel Clock: 45 MHz
	// Sensor Logic Data Rate: 180 Mpix/s
	// MIPI Data Rate: 180 Mpix/s
	// Serial data Rate: 450 Mbit/s
	// 
	// [IMAGE PARAMETERS]
	// Requested Frames Per Second: 60
	// Output Columns: 1280
	// Output Rows: 720
	// Use Binning: Unchecked
	// Cols Skipping: Checked
	// Rows Skipping: Checked
	// Blanking Computation: VB Max then HB
	// 
	// Max Frame Time: 16.6667 msec
	// Max Frame Clocks: 750000.0 clocks  (45 MHz)
	// 
	// Subsampling: 1x cols, 1x rows, Bin Mode: No
	// Horiz clks:  612 total
	// Vert  rows:  720 active + 500 blank = 1220 total
	// Extra Delay: 3360 clocks
	// Columns FOV: 1280
	// Rows FOV   : 720
	// Output Cols: 1280
	// Output Rows: 720
	// Actual Frame Clocks: 746640 clocks
	// Row Time: 13.600 usec.
	// Integration Time: 10 msec.
	// Frame time: 16.592000 msec
	// Maximum Frame Rate allowed: 99.230fps
	// Frames per Sec: 60.024 fps
	// 
	// Operation Mode: Linear
	{ .action = WRITE_REG, .addr = 0x302A, .val = 0x0005 },		//VT_PIX_CLK_DIV = 5
	{ .action = WRITE_REG, .addr = 0x302C, .val = 0x0002 },		//VT_SYS_CLK_DIV = 2
	{ .action = WRITE_REG, .addr = 0x302E, .val = 0x0003 },		//PRE_PLL_CLK_DIV = 3
	{ .action = WRITE_REG, .addr = 0x3030, .val = 0x0032 },		//PLL_MULTIPLIER = 50
	{ .action = WRITE_REG, .addr = 0x3036, .val = 0x000A },		//OP_PIX_CLK_DIV = 10
	{ .action = WRITE_REG, .addr = 0x3038, .val = 0x0002 },		//OP_SYS_CLK_DIV = 2
	{ .action = WRITE_REG, .addr = 0x30B0, .val = 0x0000 },		//DIGITAL_TEST, bits 0x4000 = 0
	{ .action = WRITE_REG, .addr = 0x31B0, .val = 0x004C },		//FRAME_PREAMBLE = 76
	{ .action = WRITE_REG, .addr = 0x31B2, .val = 0x003C },		//LINE_PREAMBLE = 60
	{ .action = WRITE_REG, .addr = 0x31B4, .val = 0x31C5 },		//MIPI_TIMING_0 = 12741
	{ .action = WRITE_REG, .addr = 0x31B6, .val = 0x214C },		//MIPI_TIMING_1 = 8524
	{ .action = WRITE_REG, .addr = 0x31B8, .val = 0x5048 },		//MIPI_TIMING_2 = 20552
	{ .action = WRITE_REG, .addr = 0x31BA, .val = 0x0186 },		//MIPI_TIMING_3 = 390
	{ .action = WRITE_REG, .addr = 0x31BC, .val = 0x8805 },		//MIPI_TIMING_4 = 34821
	{ .action = WRITE_REG, .addr = 0x3354, .val = 0x002B },		//MIPI_CNTRL = 43
	{ .action = WRITE_REG, .addr = 0x301A, .val = 0x2058 },		//RESET_REGISTER = 8280
	{ .action = WRITE_REG, .addr = 0x31AE, .val = 0x0204 },		//SERIAL_FORMAT = 516
	{ .action = WRITE_REG, .addr = 0x3002, .val = 0x00F8 },		//Y_ADDR_START = 248
	{ .action = WRITE_REG, .addr = 0x3004, .val = 0x0148 },		//X_ADDR_START = 328
	{ .action = WRITE_REG, .addr = 0x3006, .val = 0x03C7 },		//Y_ADDR_END = 967
	{ .action = WRITE_REG, .addr = 0x3008, .val = 0x0647 },		//X_ADDR_END = 1607
	{ .action = WRITE_REG, .addr = 0x300A, .val = 0x04C4 },		//FRAME_LENGTH_LINES = 1220
	{ .action = WRITE_REG, .addr = 0x300C, .val = 0x0264 },		//LINE_LENGTH_PCK = 612
	{ .action = WRITE_REG, .addr = 0x3012, .val = 0x02DF },		//COARSE_INTEGRATION_TIME = 735
	{ .action = WRITE_REG, .addr = 0x31AC, .val = 0x0A0A },		//DATA_FORMAT_BITS = 2570
	{ .action = WRITE_REG, .addr = 0x306E, .val = 0x9010 },		//DATAPATH_SELECT = 36880
	{ .action = WRITE_REG, .addr = 0x30A2, .val = 0x0001 },		//X_ODD_INC = 1
	{ .action = WRITE_REG, .addr = 0x30A6, .val = 0x0001 },		//Y_ODD_INC = 1
	{ .action = WRITE_REG, .addr = 0x3082, .val = 0x0003 },		//OPERATION_MODE_CTRL = 3
	{ .action = WRITE_REG, .addr = 0x3040, .val = 0x0000 },		//READ_MODE = 0
	{ .action = WRITE_REG, .addr = 0x31D0, .val = 0x0000 },		//COMPANDING = 0
	{ .action = WRITE_REG, .addr = 0x301A, .val = 0x2058 },		//RESET_REGISTER = 8284
	{ .action = END_TABLE }
};

const struct reg_tbl_t ar0234_720p_120fps[] = {
	// This file was generated by RegisterWizard.exe for AR0234CS.  Version: 6. 1. 11. 57619 (Build Date: Feb  8 2022)
	// 
	// [PLL PARAMETERS]
	// Target Pixel Frequency: 55.200 MHz
	// Input Clock Frequency: 27 MHz
	// 
	// Actual Pixel Clock: 55.200 MHz
	// 
	// pre_pll_clk_div (N+1 Value) = 9
	// pll_multiplier  (2M Value) = 184
	// Fvco = 552 MHz
	// vt_sys_clk_div (P1) = 2
	// vt_pix_clk_div (P2) = 5
	// op_sys_clk_div (P3) = 2
	// op_pix_clk_div (WCD)= 10
	// Serial Bit Clock: 276 MHz
	// Word Clock: 55.200 MHz
	// Pixel Clock: 55.200 MHz
	// Sensor Logic Data Rate: 220.800 Mpix/s
	// MIPI Data Rate: 220.800 Mpix/s
	// Serial data Rate: 552 Mbit/s
	// 
	// [IMAGE PARAMETERS]
	// Requested Frames Per Second: 120
	// Output Columns: 1280
	// Output Rows: 720
	// Use Binning: Unchecked
	// Cols Skipping: Checked
	// Rows Skipping: Checked
	// Blanking Computation: VB Max then HB
	// 
	// Max Frame Time: 8.33333 msec
	// Max Frame Clocks: 460000.0 clocks  (55.20 MHz)
	// 
	// Subsampling: 1x cols, 1x rows, Bin Mode: No
	// Horiz clks:  612 total
	// Vert  rows:  720 active + 26 blank = 746 total
	// Extra Delay: 3448 clocks
	// Columns FOV: 1280
	// Rows FOV   : 720
	// Output Cols: 1280
	// Output Rows: 720
	// Actual Frame Clocks: 456552 clocks
	// Row Time: 11.087 usec.
	// Integration Time: 8 msec.
	// Frame time: 8.270870 msec
	// Maximum Frame Rate allowed: 121.722fps
	// Frames per Sec: 120.101 fps
	// 
	// Operation Mode: Linear
	{ .action = WRITE_REG, .addr = 0x302A, .val = 0x0005 },		//VT_PIX_CLK_DIV = 5
	{ .action = WRITE_REG, .addr = 0x302C, .val = 0x0002 },		//VT_SYS_CLK_DIV = 2
	{ .action = WRITE_REG, .addr = 0x302E, .val = 0x0009 },		//PRE_PLL_CLK_DIV = 9
	{ .action = WRITE_REG, .addr = 0x3030, .val = 0x00B8 },		//PLL_MULTIPLIER = 184
	{ .action = WRITE_REG, .addr = 0x3036, .val = 0x000A },		//OP_PIX_CLK_DIV = 10
	{ .action = WRITE_REG, .addr = 0x3038, .val = 0x0002 },		//OP_SYS_CLK_DIV = 2
	{ .action = WRITE_REG, .addr = 0x30B0, .val = 0x0000 },		//DIGITAL_TEST, bits 0x4000 = 0
	{ .action = WRITE_REG, .addr = 0x31B0, .val = 0x0059 },		//FRAME_PREAMBLE = 89
	{ .action = WRITE_REG, .addr = 0x31B2, .val = 0x0044 },		//LINE_PREAMBLE = 68
	{ .action = WRITE_REG, .addr = 0x31B4, .val = 0x31C6 },		//MIPI_TIMING_0 = 12742
	{ .action = WRITE_REG, .addr = 0x31B6, .val = 0x318F },		//MIPI_TIMING_1 = 12687
	{ .action = WRITE_REG, .addr = 0x31B8, .val = 0x6049 },		//MIPI_TIMING_2 = 24649
	{ .action = WRITE_REG, .addr = 0x31BA, .val = 0x0207 },		//MIPI_TIMING_3 = 519
	{ .action = WRITE_REG, .addr = 0x31BC, .val = 0x8906 },		//MIPI_TIMING_4 = 35078
	{ .action = WRITE_REG, .addr = 0x3354, .val = 0x002B },		//MIPI_CNTRL = 43
	{ .action = WRITE_REG, .addr = 0x301A, .val = 0x2058 },		//RESET_REGISTER = 8280
	{ .action = WRITE_REG, .addr = 0x31AE, .val = 0x0204 },		//SERIAL_FORMAT = 516
	{ .action = WRITE_REG, .addr = 0x3002, .val = 0x00F8 },		//Y_ADDR_START = 248
	{ .action = WRITE_REG, .addr = 0x3004, .val = 0x0148 },		//X_ADDR_START = 328
	{ .action = WRITE_REG, .addr = 0x3006, .val = 0x03C7 },		//Y_ADDR_END = 967
	{ .action = WRITE_REG, .addr = 0x3008, .val = 0x0647 },		//X_ADDR_END = 1607
	{ .action = WRITE_REG, .addr = 0x300A, .val = 0x02EA },		//FRAME_LENGTH_LINES = 746
	{ .action = WRITE_REG, .addr = 0x300C, .val = 0x0264 },		//LINE_LENGTH_PCK = 612
	{ .action = WRITE_REG, .addr = 0x3012, .val = 0x02D1 },		//COARSE_INTEGRATION_TIME = 721
	{ .action = WRITE_REG, .addr = 0x31AC, .val = 0x0A0A },		//DATA_FORMAT_BITS = 2570
	{ .action = WRITE_REG, .addr = 0x306E, .val = 0x9010 },		//DATAPATH_SELECT = 36880
	{ .action = WRITE_REG, .addr = 0x30A2, .val = 0x0001 },		//X_ODD_INC = 1
	{ .action = WRITE_REG, .addr = 0x30A6, .val = 0x0001 },		//Y_ODD_INC = 1
	{ .action = WRITE_REG, .addr = 0x3082, .val = 0x0003 },		//OPERATION_MODE_CTRL = 3
	{ .action = WRITE_REG, .addr = 0x3040, .val = 0x0000 },		//READ_MODE = 0
	{ .action = WRITE_REG, .addr = 0x31D0, .val = 0x0000 },		//COMPANDING = 0
	{ .action = WRITE_REG, .addr = 0x301A, .val = 0x2058 },		//RESET_REGISTER = 8284
	{ .action = END_TABLE }
};

const struct reg_tbl_t ar0234_480p_120fps[] = {
	// This file was generated by RegisterWizard.exe for AR0234CS.  Version: 6. 1. 11. 57619 (Build Date: Feb  8 2022)
	// 
	// [PLL PARAMETERS]
	// Target Pixel Frequency: 45 MHz
	// Input Clock Frequency: 27 MHz
	// 
	// Actual Pixel Clock: 45 MHz
	// 
	// pre_pll_clk_div (N+1 Value) = 3
	// pll_multiplier  (2M Value) = 50
	// Fvco = 450 MHz
	// vt_sys_clk_div (P1) = 2
	// vt_pix_clk_div (P2) = 5
	// op_sys_clk_div (P3) = 2
	// op_pix_clk_div (WCD)= 10
	// Serial Bit Clock: 225 MHz
	// Word Clock: 45 MHz
	// Pixel Clock: 45 MHz
	// Sensor Logic Data Rate: 180 Mpix/s
	// MIPI Data Rate: 180 Mpix/s
	// Serial data Rate: 450 Mbit/s
	// 
	// [IMAGE PARAMETERS]
	// Requested Frames Per Second: 120
	// Output Columns: 1280
	// Output Rows: 960
	// Use Binning: Unchecked
	// Cols Skipping: Checked
	// Rows Skipping: Checked
	// Blanking Computation: VB Max then HB
	// 
	// Max Frame Time: 8.33333 msec
	// Max Frame Clocks: 375000.0 clocks  (45 MHz)
	// 
	// Subsampling: 2x cols, 2x rows, Bin Mode: No
	// Horiz clks:  612 total
	// Vert  rows:  480 active + 127 blank = 607 total
	// Extra Delay: 3516 clocks
	// Columns FOV: 1280
	// Rows FOV   : 960
	// Output Cols: 640
	// Output Rows: 480
	// Actual Frame Clocks: 371484 clocks
	// Row Time: 13.600 usec.
	// Integration Time: 8 msec.
	// Frame time: 8.255200 msec
	// Maximum Frame Rate allowed: 146.765fps
	// Frames per Sec: 120.146 fps
	// 
	// Operation Mode: Linear
	{ .action = WRITE_REG, .addr = 0x302A, .val = 0x0005 },		//VT_PIX_CLK_DIV = 5
	{ .action = WRITE_REG, .addr = 0x302C, .val = 0x0002 },		//VT_SYS_CLK_DIV = 2
	{ .action = WRITE_REG, .addr = 0x302E, .val = 0x0003 },		//PRE_PLL_CLK_DIV = 3
	{ .action = WRITE_REG, .addr = 0x3030, .val = 0x0032 },		//PLL_MULTIPLIER = 50
	{ .action = WRITE_REG, .addr = 0x3036, .val = 0x000A },		//OP_PIX_CLK_DIV = 10
	{ .action = WRITE_REG, .addr = 0x3038, .val = 0x0002 },		//OP_SYS_CLK_DIV = 2
	{ .action = WRITE_REG, .addr = 0x30B0, .val = 0x0000 },		//DIGITAL_TEST, bits 0x4000 = 0
	{ .action = WRITE_REG, .addr = 0x31B0, .val = 0x004C },		//FRAME_PREAMBLE = 76
	{ .action = WRITE_REG, .addr = 0x31B2, .val = 0x003C },		//LINE_PREAMBLE = 60
	{ .action = WRITE_REG, .addr = 0x31B4, .val = 0x31C5 },		//MIPI_TIMING_0 = 12741
	{ .action = WRITE_REG, .addr = 0x31B6, .val = 0x214C },		//MIPI_TIMING_1 = 8524
	{ .action = WRITE_REG, .addr = 0x31B8, .val = 0x5048 },		//MIPI_TIMING_2 = 20552
	{ .action = WRITE_REG, .addr = 0x31BA, .val = 0x0186 },		//MIPI_TIMING_3 = 390
	{ .action = WRITE_REG, .addr = 0x31BC, .val = 0x8805 },		//MIPI_TIMING_4 = 34821
	{ .action = WRITE_REG, .addr = 0x3354, .val = 0x002B },		//MIPI_CNTRL = 43
	{ .action = WRITE_REG, .addr = 0x301A, .val = 0x2058 },		//RESET_REGISTER = 8280
	{ .action = WRITE_REG, .addr = 0x31AE, .val = 0x0204 },		//SERIAL_FORMAT = 516
	{ .action = WRITE_REG, .addr = 0x3002, .val = 0x0080 },		//Y_ADDR_START = 128
	{ .action = WRITE_REG, .addr = 0x3004, .val = 0x0148 },		//X_ADDR_START = 328
	{ .action = WRITE_REG, .addr = 0x3006, .val = 0x043F },		//Y_ADDR_END = 1087
	{ .action = WRITE_REG, .addr = 0x3008, .val = 0x0647 },		//X_ADDR_END = 1607
	{ .action = WRITE_REG, .addr = 0x300A, .val = 0x025F },		//FRAME_LENGTH_LINES = 607
	{ .action = WRITE_REG, .addr = 0x300C, .val = 0x0264 },		//LINE_LENGTH_PCK = 612
	{ .action = WRITE_REG, .addr = 0x3012, .val = 0x024C },		//COARSE_INTEGRATION_TIME = 588
	{ .action = WRITE_REG, .addr = 0x31AC, .val = 0x0A0A },		//DATA_FORMAT_BITS = 2570
	{ .action = WRITE_REG, .addr = 0x306E, .val = 0x9010 },		//DATAPATH_SELECT = 36880
	{ .action = WRITE_REG, .addr = 0x30A2, .val = 0x0003 },		//X_ODD_INC = 3
	{ .action = WRITE_REG, .addr = 0x30A6, .val = 0x0003 },		//Y_ODD_INC = 3
	{ .action = WRITE_REG, .addr = 0x3082, .val = 0x0003 },		//OPERATION_MODE_CTRL = 3
	{ .action = WRITE_REG, .addr = 0x3040, .val = 0x0000 },		//READ_MODE = 0
	{ .action = WRITE_REG, .addr = 0x31D0, .val = 0x0000 },		//COMPANDING = 0
	{ .action = WRITE_REG, .addr = 0x301A, .val = 0x2058 },		//RESET_REGISTER = 8284
	{ .action = END_TABLE }
};
