#!/bin/bash

# Create symlinks for ISP configurations.
isp_symlinks()
{
    cd /var/nvidia/nvcam/settings/
    for p in {0..9} {A..F}; do
        TARGET_OV10640="d3_${p}_ov10640.isp"
        TARGET_IMX390="d3_${p}_imx390.isp"
        TARGET_IMX390RCM="d3_${p}_imx390rcm.isp"
        TARGET_IMX490FPD="d3_${p}_imx490fpd.isp"

        if ! [ -e "$TARGET_OV10640" ]; then
            ln -s ov10640.isp "$TARGET_OV10640"
        fi
        if ! [ -e "$TARGET_IMX390" ]; then
            ln -s imx390.isp "$TARGET_IMX390"
        fi
        if ! [ -e "$TARGET_IMX390RCM" ]; then
            ln -s imx390.isp "$TARGET_IMX390RCM"
        fi
        if ! [ -e "$TARGET_IMX490FPD" ]; then
            ln -s imx490.isp "$TARGET_IMX490FPD"
        fi
    done
}

echo 'Updating ISP overrides...'
isp_symlinks

echo 'Updating boot logo...'
dd if=/boot/boot-logo.blob of=/dev/disk/by-partlabel/BMP

echo 'Updating libnvscf...'
cp /usr/lib/aarch64-linux-gnu/tegra/libnvscf.so /usr/lib/aarch64-linux-gnu/tegra/libnvscf.so.backup
cp /usr/lib/d3-jetson-utils/libnvscf.so /usr/lib/aarch64-linux-gnu/tegra/libnvscf.so

echo 'Please select the appropriate DTB for the hardware you plan to use...'
d3-install-dtb
