#!/bin/bash

# Remove symlinks created in postinst
mode=$1
case $mode in
    upgrade)
    ;;
    disappear)
    ;;
    remove)
        if [ -e /usr/lib/aarch64-linux-gnu/tegra/libnvscf.so.backup ]; then
            mv /usr/lib/aarch64-linux-gnu/tegra/libnvscf.so.backup /usr/lib/aarch64-linux-gnu/tegra/libnvscf.so
        fi
    ;;
    purge)
    ;;
    failed-upgrade)
    ;;
    abort-install)
        if [ -e /usr/lib/aarch64-linux-gnu/tegra/libnvscf.so.backup ]; then
            mv /usr/lib/aarch64-linux-gnu/tegra/libnvscf.so.backup /usr/lib/aarch64-linux-gnu/tegra/libnvscf.so
        fi
    ;;
    abort-upgrade)
    ;;
esac
exit 0

