#!/bin/bash

# Ignore SIGHUP, SIGTERM
trap "" SIGHUP SIGTERM

# MaxN power model
sudo nvpmodel -m 0

# Max clocks
sudo jetson_clocks

# Assign overlays
# This might not work the same for Xavier
sudo $(dirname $0)/overlay-assign

# Stop UI because we need the overlay
sudo telinit 3

# Run the pipeline
$(dirname $0)/camera-mosaic
